### ISSUE TITLE
Cannot write to a BufferedStream 

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/peds#3]
2018/05/31 20:34:38:004 [DEBUG] Makaretu.Dns.DotClient - using dns server 'cloudflare-dns.com' 2606:4700:4700::1111.
2018/05/31 20:34:38:006 [DEBUG] Makaretu.Dns.DotClient - query #43007 for 'external.fhlz1-1.fna.fbcdn.net AAAA'
2018/05/31 20:34:38:014 [DEBUG] Makaretu.Dns.DotClient - query #43012 for 'video.fhlz1-1.fna.fbcdn.net AAAA'
2018/05/31 20:34:38:007 [DEBUG] Makaretu.Dns.DotClient - query #43011 for 'scontent.fhlz1-1.fna.fbcdn.net AAAA'
2018/05/31 20:34:38:025 [DEBUG] Makaretu.Dns.DotClient - query #43016 for 'external.fhlz1-1.fna.fbcdn.net AAAA'
2018/05/31 20:34:38:028 [DEBUG] Makaretu.Dns.DotClient - Got response #43007 NoError
2018/05/31 20:34:38:042 [DEBUG] Makaretu.Dns.DotClient - query #43017 for 'static.xx.fbcdn.net A'
2018/05/31 20:34:38:011 [DEBUG] Makaretu.Dns.DotClient - query #43013 for 'static.xx.fbcdn.net AAAA'
2018/05/31 20:34:38:054 [DEBUG] Makaretu.Dns.DotClient - query #43018 for 'scontent.fhlz1-1.fna.fbcdn.net A'
2018/05/31 20:34:38:011 [DEBUG] Makaretu.Dns.DotClient - query #43009 for 'video.fhlz1-1.fna.fbcdn.net A'
2018/05/31 20:34:38:006 [DEBUG] Makaretu.Dns.DotClient - query #43010 for 'scontent.fhlz1-1.fna.fbcdn.net A'
2018/05/31 20:34:38:011 [DEBUG] Makaretu.Dns.DotClient - query #43015 for 'scontent.xx.fbcdn.net AAAA'
2018/05/31 20:34:38:067 [DEBUG] Makaretu.Dns.DotClient - query #43019 for 'video.fhlz1-1.fna.fbcdn.net A'
2018/05/31 20:34:38:014 [DEBUG] Makaretu.Dns.DotClient - query #43008 for 'static.xx.fbcdn.net A'
2018/05/31 20:34:38:072 [DEBUG] Makaretu.Dns.DotClient - query #43020 for 'static.xx.fbcdn.net AAAA'
2018/05/31 20:34:38:049 [DEBUG] Makaretu.Dns.DotClient - Got response #43012 NoError
2018/05/31 20:34:38:077 [DEBUG] Makaretu.Dns.DotClient - query #43021 for 'video.fhlz1-1.fna.fbcdn.net AAAA'
2018/05/31 20:34:38:077 [DEBUG] Makaretu.Dns.DotClient - Got response #43011 NoError
2018/05/31 20:34:38:078 [DEBUG] Makaretu.Dns.DotClient - Got response #43016 NoError
2018/05/31 20:34:38:079 [ERROR] Makaretu.Dns.Peds.UdpServer 
>- System.IO.IOException: The write operation failed, see inner exception. ---> System.NotSupportedException: Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.
   at System.IO.BufferedStream.ClearReadBufferBeforeWrite()
   at System.IO.BufferedStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Makaretu.Dns.DotClient.<QueryAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Makaretu.Dns.Peds.UdpServer.<Process>d__17.MoveNext()
2018/05/31 20:34:38:083 [DEBUG] Makaretu.Dns.DotClient - Got response #43017 NoError
2018/05/31 20:34:38:091 [DEBUG] Makaretu.Dns.DotClient - query #43022 for 'scontent.fhlz1-1.fna.fbcdn.net AAAA'
2018/05/31 20:34:38:091 [DEBUG] Makaretu.Dns.DotClient - Got response #43013 NoError
2018/05/31 20:34:38:096 [DEBUG] Makaretu.Dns.DotClient - query #43023 for 'scontent.xx.fbcdn.net A'
2018/05/31 20:34:38:099 [DEBUG] Makaretu.Dns.DotClient - query #43024 for 'scontent.xx.fbcdn.net AAAA'
2018/05/31 20:34:38:108 [DEBUG] Makaretu.Dns.DotClient - Got response #43018 NoError
2018/05/31 20:34:38:109 [DEBUG] Makaretu.Dns.DotClient - Got response #43009 NoError
2018/05/31 20:34:38:110 [DEBUG] Makaretu.Dns.DotClient - Got response #43010 NoError
2018/05/31 20:34:38:110 [DEBUG] Makaretu.Dns.DotClient - Got response #43015 NoError
2018/05/31 20:34:38:113 [DEBUG] Makaretu.Dns.DotClient - Got response #43019 NoError
2018/05/31 20:34:38:114 [DEBUG] Makaretu.Dns.DotClient - Got response #43008 NoError
2018/05/31 20:34:38:115 [DEBUG] Makaretu.Dns.DotClient - Got response #43020 NoError
2018/05/31 20:34:38:125 [DEBUG] Makaretu.Dns.DotClient - Retying query #43022
2018/

**Comment by richardschneider** [comment]
This is an issue with `DotClient` in https://github.com/richardschneider/net-udns
