### ISSUE TITLE
Task cancelled

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/peds#5]
2018/06/01 12:43:51:933 [ERROR] Makaretu.Dns.Peds.UdpServer - System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nito.AsyncEx.TaskExtensions.<DoWaitAsync>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Makaretu.Dns.DotClient.<QueryAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Makaretu.Dns.Peds.UdpServer.<Process>d__17.MoveNext()
2018/06/01 12:43:52:085 [ERROR] Makaretu.Dns.Peds.UdpServer - System.Threading.Tasks.TaskCanceledException: A task was ca

**Comment by richardschneider** [comment]
Looks like the internet connection went down.
