### ISSUE TITLE
netsh fails

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/peds#6]
Failing when closing peds

CTRL-C
2018/06/02 11:41:40:394 [DEBUG] netsh - interface ipv4 delete dns "Ethernet 2" all
2018/06/02 11:41:40:395 [DEBUG] netsh - interface ipv4 add dns "Ethernet 2" 127.0.0.1 validate=no
2018/06/02 11:41:40:395 [DEBUG] netsh - interface ipv6 delete dns "Ethernet 2" all
2018/06/02 11:41:40:395 [DEBUG] netsh - interface ipv6 add dns "Ethernet 2" ::1 validate=no
2018/06/02 11:41:40:395 [DEBUG] netsh - interface ipv6 delete dns "Npcap Loopback Adapter" all
2018/06/02 11:41:40:395 [DEBUG] netsh - interface ipv6 add dns "Npcap Loopback Adapter" fec0:0:0:ffff::1%1 validate=no
2018/06/02 11:41:40:395 [DEBUG] netsh - interface ipv6 add dns "Npcap Loopback Adapter" fec0:0:0:ffff::2%1 validate=no
2018/06/02 11:41:40:395 [DEBUG] netsh - interface ipv6 add dns "Npcap Loopback Adapter" fec0:0:0:ffff::3%1 validate=no
2018/06/02 11:41:40:395 [DEBUG] netsh - interface ipv4 delete dns "Local Area Connection* 4" all
2018/06/02 11:41:40:395 [DEBUG] netsh - interface ipv4 add dns "Local Area Connection* 4" 127.0.0.1 validate=no
2018/06/02 11:41:40:395 [DEBUG] netsh - interface ipv6 delete dns "Local Area Connection* 4" all
2018/06/02 11:41:40:395 [DEBUG] netsh - interface ipv6 add dns "Local Area Connection* 4" ::1 validate=no
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv4 delete dns "Local Area Connection* 5" all
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv4 add dns "Local Area Connection* 5" 127.0.0.1 validate=no
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv6 delete dns "Local Area Connection* 5" all
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv6 add dns "Local Area Connection* 5" ::1 validate=no
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv4 delete dns "Wi-Fi" all
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv4 add dns "Wi-Fi" 1.1.1.1 validate=no
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv4 add dns "Wi-Fi" 1.0.1.1 validate=no
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv6 delete dns "Wi-Fi" all
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv6 add dns "Wi-Fi" ::1 validate=no
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv4 delete dns "Bluetooth Network Connection" all
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv4 add dns "Bluetooth Network Connection" 127.0.0.1 validate=no
2018/06/02 11:41:40:396 [DEBUG] netsh - interface ipv6 delete dns "Bluetooth Network Connection" all
2018/06/02 11:41:40:397 [DEBUG] netsh - interface ipv6 add dns "Bluetooth Network Connection" ::1 validate=no

Unhandled Exception: System.Exception: netsh failed with exit code 1.
   at Makaretu.Dns.Peds.NetShell.Run()
   at Makaretu.Dns.Peds.Nic.Dispose()
   at Makaretu.Dns.Peds.Program.Stop()
   at Makaretu.Dns.Peds.Program.<RunAsync>b__4_0(Object s, ConsoleCancelEventArgs e)
   at System.Console.ControlCDelegate(Object data)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
^

**Comment by richardschneider** [comment]
The issue is with the scope ID (`%1`) in the address `fec0:0:0:ffff::1%1 `. Also,  `fec0` is [obsolete](https://en.wikipedia.org/wiki/IPv6_address#Deprecated_and_obsolete_addresses_2).

netsh does not support a scope ID in an IPv6 address.
